development:
  adapter: postgresql
  database: kigendan_dev
  username: rails
  password: 4d003d1435f0827cfe18ac2d2a3979e7
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: kigendan_test
  username: rails
  password: 4d003d1435f0827cfe18ac2d2a3979e7
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: kigendan
  username: rails
  password: 4d003d1435f0827cfe18ac2d2a3979e7
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000